### ISSUE TITLE
fix: bugs and clarify behavior introduced by #957

### ISSUE THREAD

**Issue by tangjeff0** [athensresearch/athens#1015]
- [X] multiple block refs #1012
- [ ] allow for spaces inside image #1013
- [ ] multiple LaTeX fragments, e.g. `$$a$$ and $$b$$` #1017
- [ ] no need for spaces around block refs, e.g. `.((c1c466055))`
- [ ] this LaTeX should work (yifan) `$$G, \mu$$ and Poisson's ratio $$\nu$$`

**Comment by yifanyin** [comment]
I think No.2 and 5 are essentially the same.

As I look into the Katex docs, I did find that some functions require extra `$`, like [vertical layout](https://katex.org/docs/supported.html#vertical-layout) and some [styling](https://katex.org/docs/supported.html#style-color-size-and-font). Not very common for my use, though.
I do love to see the space omitted around the block reference. But that's just me sometimes collecting notes in Mandarin. Without the space the paragraphs look slightly prettier that's all.
