### ISSUE TITLE
Bugs found for Find or Create input

### ISSUE THREAD

**Issue by BenchLord** [athensresearch/athens#1030]
As you can see in the video there are a few interesting things
1) Find or Create input gives nasty error when no notes exist
2) If a daily note exists the Find or Create form will take you there if `Enter` is pressed fast enough. This happens even if you type in the correct note name in the form.

Not bugs necessarily but other few things:
1) Empty bullets stick around and are shown on the Body column of the All Pages page
2) The option menu for notes (add/remove shortcut, show local graph, delete page) should also be available on the All Pages page

https://user-images.githubusercontent.com/6004385/115935377-4b253280-a450-11eb-9afc-3600e7899326.mov

**Comment by avidrucker** [comment]
@BenchLord Thank you for the clear explanation and demo video.

**Comment by sid597** [comment]
- [x] Find or Create input gives nasty error when no notes exist : Could not reproduce in beta.89 can be tested in the athens demo [here](https://athensresearch.github.io/athens/)
- [x] If a daily note exists the Find or Create form will take you there if Enter is pressed fast enough. This happens even if you type in the correct note name in the form. : This was resolved by @juniusfree 
- [x] Empty bullets stick around and are shown on the Body column of the All Pages page : fixed by @shanberg
- [X] The option menu for notes (add/remove shortcut, show local graph, delete page) should also be available on the All Pages page : More like a feature request, can create a new discussion around this, add/remove shortcut is already mentioned in the discussions.
