### ISSUE TITLE
Parser

### ISSUE THREAD

**Issue by jsmorabito** [athensresearch/athens#1122]
Notes
- Related to New Editor to Replace Raw Textareas #1091 
- previous issue: Parser #94 

### Current State
- 3 stage parser

### Goal State
- figure out how to integrate with content editable

### Bugs
- [ ] #1107 Small parser problem : bold + italics don't work if nothing before in a block
- [x] #1059 Parser: cannot combine component with fenced code block
- [ ] #1058 Parser: fails to parse some page links
- [x] #1057 Parser: underscores in inline URLs
- [ ] #587 A preformatted code block containing ` is not seen as a code block f/parser t/bug
- [x] #1036 Miscellaneous parser bugs
- [x] #962 Links don't work when placed inside **bold markers**

### Enhancements
- [ ] #989 Integrate with CodeMirror for code blocks
- [ ] #709 Parse a larger set of permissible URLs f/parser

**Comment by sid597** [comment]
#1054 should also be added

**Comment by tangjeff0** [comment]
Not sure if we will continue using epics. If all the small issues have the `f/parser` label, then we should just use that label: https://github.com/athensresearch/athens/labels/f%2Fparser

**Comment by jsmorabito** [comment]
closing for now. to reiterate from community call today: the maintenance cost of epic issues is not currently offset or outweighed by the benefit of them (which is that its a consolidated place for other issues related to the top level issue which allows for a quick glance at the state of a feature or system with an additional description in the epic issue)
