### ISSUE TITLE
Shared semantic events

### ISSUE THREAD

**Issue by tangjeff0** [athensresearch/athens#1342]
Migrate events to `common-events`:

- [X] `:page/create` #1404 
- [x] #1406
- [x] `:page/merge`
- [x] `:page/rename`
- [x] `:page/reindex-left-sidebar`
- [x] `:page/add-shortcut`
- [x] `:page/remove-shortcut`
- [x] `:undo`
- [x] `:redo`
- [x] #1416
- [x] `:backspace`
    - Sounds like a wrong abstraction, would be better to have events for different things that backspace can generate, delete a block or recursive delete a block maybe
    - [x] #1425
    - [x] #1426
- [x] `:split-block-to-children`
- [x] `:enter/add-child`
- [x] `:enter/split-block`
- [x] `:enter/bump-up`
- [x] `:enter/new-block`
- [x] `:enter/open-block-and-child`
- [x] `:indent`
- [x] #1405
- [x] `:unindent`
- [x] #1407
- [x] `:drop`
    - [x] `:drop-link/child`
    - [x] #1408
    - [x] `:drop-link/diff`
    - [x] `:drop/child`
    - [x] #1409
    - [x] `:drop/diff`
- [x] `:drop-multi`
    - [x] `:drop-multi/child`
    - [x] #1410
    - [x] #1411
    - [x] #1412
- [x]  `:paste-verbatim`
- [x] #1413
- [x] `:left-sidebar/drop-above`
- [x] `:left-sidebar/drop-below`
- [x] `:unlinked-references/link`
- [x] `:unlinked-references/link-all`
- [x] #1414
- [x] #1452
- [x] #1453
- [x] #1454
- [x] #1455
- [x] #1456

THEN TEST: #1343

**Comment by neotyk** [comment]
## Events Migration Path

- **Define event**
    - Step 1: Look at how the event you want to migrate works
        - Sometimes you'll notice that some information is too much,
like with `:page/delete` where we pass `uid` (necessary) and `title` that should be discovered during event resolution.
    - Step 2: Define new event schema in `athens.common-events.schema`
        - Add new `event-type` to enum
        - Define `:event/args` schema for your event
        - Add dispatch definition in `event`,
Make sure you're merging with `event-common`
    - Step 3: Create event builder in `common-events`
        - Make sure you're using `:event/last-tx`
- **Test the event** 
    - Step 1: Where to test
        - All `common-events` tests are located in `test/athens/common_events`
        - Is there a test file that deals with testing similar things?
            - Like for `:page/delete` `page_test.clj` already exsits so I'll add tests there
            - If you're implementing new event category, that has no tests yet, create new `*_test.clj` file, and write your tests there
    - Step 2: How to test
        - Create event using a builder fn you've created in `common-events` to test the event
        - Introduce event resolution fn
            - For now let's just make a placeholder from it,
so just multimethod definition that doesn't yet resolve the event
        - Time to `transact` result of resolution
        - And then check the assumptions about the state of DB
            - After removing the page I should not be able to find neither page, blocks inside of it and references should be removed
            - All these assertion should be failing at this point, since event resolution is not implemented
    - Step 3: Fix the test
        - Currently test is failing, it's time now to port old event code to resolution fn
        - While porting you might discover testing scenarios that you didn't think of before, document these as tests
- **Use new event**
    - Step 1: Locally
        - Use event builder fn and resolution fn to create transactions
        - `transact`
        - dispatch any followup events
    - Step 2: Remotely
        - Check if we're in Lan Party mode
        - if so dispatch it to dedicated `:remote/*` event
        - Implement new `:remote/*' event
            - Make sure to
                - Build event using `common-events` builder fn you've created recently
                - dispatch `:remote/await-ack`
                - and `:remote/register-followup` if there is any
                    - In current design you'll need to create dedicated event to be triggered for followup.
                    - followup you'll register is going to be used as `:fx` value in result of `rf/reg-event-fx`
                    - Common use case, simply dispatch events:
                        - ``` clojure
                           [[:dispatch [:event-name args]]]
                           ```
                - use `:remote/send-event!` to send the event to the server
    - Step 3: Voila

**Comment by sid597** [comment]
@filipesilva We also need to add the following to migrate events list which [Alex Found out](https://github.com/neotyk/athens/commit/4843fdc06a1e1cd106e103e5d233886dd82ec3ed):

- [ ] in `todo-on-click` fn use `:block/save` event
- [ ] in `handle-arrow-key` fn add add `:block/open` & `:block/close` events
- [ ] in `toggle` fn add `:block/open` and `:block/close` events
- [ ] in `transact-string` use `:block/save` event
- [ ] in `handle-new-first-child-block-click` find out what event should be used, Alex's hunch is `:block/add-child`
