### ISSUE TITLE
RTC Alpha-1 QA

### ISSUE THREAD

**Issue by filipesilva** [athensresearch/athens#1427]
This meta-issue will scope and track work from testing the RTC Alpha-1 release.

## RTC Server

- [ ] standalone JAR runs

## DB Switcher

Test the following things after #1429 

- [ ] Db switcher: Check if we can switch between local and remote DB
- [ ] Local storage: After refactor check if values that should be persisted are actually being persisted
- [ ] FIlesystem: Check if adding, moving, deleting works for the filesystem
- [ ] Boot: Check if boot works for both local and remote setting

All of the above are also interlinked so can test them in the following way : 
 - [ ]  Add a new DB: Tests Filesystem, boot, and DB switcher
 - [ ]  Restart Athens to see if the newly added DB is there along with all the previous DB: Tests local storage, boot 
 - [ ]  Open a new DB : Tests Filesystem, boot, DB switcher
 - [ ]  Restart Athens to check if DB added in the last session is still there and is selected by default: Tests local storage
 - [ ]  Move the current DB: Tests Filesystem, DB switcher
 - [ ]  Delete a DB: Tests Filesystem, DB switcher
 - [ ]  Restart Athens and check if delete is reflected in the list : Tests local storage
 - [ ]  Select a DB from the list: Tests Filesystem, boot, and DB switcher
 - [ ]  Check sync: Make changes in the current DB and check if the sync is working
 - [ ]  Change DB while sync: Should not be able to switch DB while the sync is in progress in current DB
 - [ ]  Select a db which is deleted from disk : Tests DB switcher and Filesystem
 - [ ]  Delete the last DB in list: Should not be able to delete the last remaining DB in the list : Tests DB switcher
 - [ ]  Remote DB: Some of the above tests can also be done keeping remote db in mind

**Comment by sid597** [comment]
- [ ] Join a server
    - [ ] Connect from different Operating systems
- [ ] DB Dump
    - [ ] Fresh server: A new server with no interaction with clients will have a welcome page just like a fresh Athens installation
    - [ ] Server which already is used by other users so data is there and when a new user connects all this data should be dumped instead of Welcome page


- [ ] Transact events
    - [ ] Testing common events if all of them are working as expected or not 
        - maybe only basics tests for each event is sufficient we are not testing the event but if the event is transacted to server. If transaction is happening we can thoroughly test these events locally also.
    - [ ] Testing delivery of events
        - [ ] Is the sequence of events transacted correct  
            - NOTE: No. of events transacted to user X depends how far the user X is from the server's latest event. Even so the goal is to check if the sequence transacted to all the user upto some point is same or not
            - [ ] When one user is producer and all other are consumers. 
            - [ ] When all the users involved are both producers and consumers. 
    - [ ] Latency of the transacted events
        - [ ] How long does it take for producer to consumer, can be tested without knowing actual *ms* 
            - [ ] Producer transacts a defined sequence of events say 20 events with their normal speed and the consumer should not experience lag (as perceived by them). Initially can start with 2 users but can increase the no. of users till someone starts experiencing lag. 
            - NOTE: this is still a single producer, can try to do this where all the users are producers and consumers. I suspect the case where all the users are both consumers and producers can be tested only with small group in a constrained environment with natural flow. 
        - [ ] There are 2 users one with fast network other with slow network (relatively). If both are making changes to same block, will the user with slower network essentially becomes consumer because of their changes getting rejected due to newer changes made by fast network user?
- [ ] Disconnect
    - [ ] When a user disconnects is the connection actually disconnected? 
        - Can be tested if one producer and all other consumers where the events to be transacted are pre-defined. one user disconnects after say event 10 out of 20 events they should not receive events 11 and onwards.

**Comment by filipesilva** [comment]
Putting this comment up so I can follow the test plan and report results:

## RTC Server

- [ ] standalone JAR runs
- [ ] Join a server
    - [ ] Connect from different Operating systems
- [ ] DB Dump
    - [ ] Fresh server: A new server with no interaction with clients will have a welcome page just like a fresh Athens installation
    - [ ] Server which already is used by other users so data is there and when a new user connects all this data should be dumped instead of Welcome page
- [ ] Transact events
    - [ ] Testing common events if all of them are working as expected or not 
        - maybe only basics tests for each event is sufficient we are not testing the event but if the event is transacted to the server. If the transaction is happening we can thoroughly test these events locally also.
    - [ ] Latency of the transacted events
        - [ ] How long does it take for a producer to consumer, can be tested without knowing actual *ms* 
            - [ ] Producer transacts a defined sequence of events say 20 events with their normal speed and the consumer should not experience lag (as perceived by them). Initially can start with 2 users but can increase the no. of users till someone starts experiencing lag. 
        - [ ] There are 2 users one with a fast network other with a slow network (relatively). If both are making changes to the same block, will the user with a slower network essentially become consumers because of their changes getting rejected due to newer changes made by fast network users?
- [ ] Disconnect
    - [ ] When a user disconnects is the connection actually disconnected? 
        - Can be tested if one producer and all other consumers where the events to be transacted are pre-defined. one user disconnects after say event 10 out of 20 events they should not receive events 11 and onwards.  

## DB Switcher

Test the following things after #1429 

- [ ] Db switcher: Check if we can switch between local and remote DB
- [ ] Local storage: After refactor check if values that should be persisted are actually being persisted
- [ ] FIlesystem: Check if adding, moving, deleting works for the filesystem
- [ ] Boot: Check if boot works for both local and remote setting

All of the above are also interlinked so can test them in the following way : 
 - [ ]  Add a new DB: Tests Filesystem, boot, and DB switcher
 - [ ]  Restart Athens to see if the newly added DB is there along with all the previous DB: Tests local storage, boot 
 - [ ]  Open a new DB : Tests Filesystem, boot, DB switcher
 - [ ]  Restart Athens to check if DB added in the last session is still there and is selected by default: Tests local storage
 - [ ]  Move the current DB: Tests Filesystem, DB switcher
 - [ ]  Delete a DB: Tests Filesystem, DB switcher
 - [ ]  Restart Athens and check if delete is reflected in the list : Tests local storage
 - [ ]  Select a DB from the list: Tests Filesystem, boot, and DB switcher
 - [ ]  Check sync: Make changes in the current DB and check if the sync is working
 - [ ]  Change DB while sync: Should not be able to switch DB while the sync is in progress in current DB
 - [ ]  Select a db which is deleted from disk : Tests DB switcher and Filesystem
 - [ ]  Delete the last DB in list: Should not be able to delete the last remaining DB in the list : Tests DB switcher
 - [ ]  Remote DB: Some of the above tests can also be done keeping remote db in mind

**Comment by sid597** [comment]
> Add a new DB: Tests Filesystem, boot, and DB switcher

Result : success

**Comment by sid597** [comment]
>  Restart Athens to see if the newly added DB is there along with all the previous DB: Tests local storage, boot

Result: success 

Please use thumbs up if you got the same result otherwise thumbs down and add a comment for what you found.

**Comment by sid597** [comment]
>  Open a new DB : Tests Filesystem, boot, DB switcher

Result: Success 

Please use thumbs up if you got the same result otherwise thumbs down and add a comment for what you found.

**Comment by sid597** [comment]
> Restart Athens to check if DB added in the last session is still there and is selected by default: Tests local storage

Result: Success 

Please use thumbs up if you got the same result otherwise thumbs down and add a comment for what you found.

**Comment by sid597** [comment]
> Delete a DB: Tests Filesystem, DB switcher

Result: Error 

 After I click on `Delete` button, a couple of seconds later I get an error saying _No such file or directory _

**Comment by sid597** [comment]
>  Restart Athens and check if delete is reflected in the list : Tests local storage

Result: Success

**Comment by sid597** [comment]
>  Select a DB from the list: Tests Filesystem, boot, and DB switcher

Result: Success

**Comment by sid597** [comment]
> Check sync: Make changes in the current DB and check if the sync is working

Resut: Success

**Comment by sid597** [comment]
>  Change DB while sync: Should not be able to switch DB while the sync is in progress in current DB

Result: Success

**Comment by sid597** [comment]
> Select a db which is deleted from disk: Tests DB switcher and Filesystem

Result: Success

**Comment by sid597** [comment]
> Delete the last DB in list: Should not be able to delete the last remaining DB in the list : Tests DB switcher

Result: Success

**Comment by juniusfree** [comment]
Tested events:
1. :page/create
2. :page/rename
3. :page/merge
4. :page/delete
5. :block/save
6. :enter/new-block
7. :enter/add-child
8. :enter/bump-up
9. :enter/open-block-add-child
10. :split-block-to-children
11. :enter/split-block
12. :unindent

Bugs reported:
1. https://github.com/athensresearch/athens/issues/1499
2. https://github.com/athensresearch/athens/issues/1500
3. https://github.com/athensresearch/athens/issues/1501
4. https://github.com/athensresearch/athens/issues/1502
5. https://github.com/athensresearch/athens/issues/1503
