### ISSUE TITLE
Drag and Drop / Block Selection

### ISSUE THREAD

**Issue by tangjeff0** [athensresearch/athens#241]
# Tasks

- [x] visual drop area indicator - [demo](https://www.loom.com/share/353fb797a02c4933a601877b35c0ebbd) - #264 
   - above
   - below
   - child (for block)
- [x] multiple block selection - [demo](https://www.loom.com/share/063f09ee3ab5428188d6793c9eb20f06) - #270
  - across sibling blocks
   - across different parents / block depths
- [x] find greatest common ancestor for nested blocks to prevent double selection/opacity - #326

# Drag n Drop

Re-ordering lists with drag n drop shows up in 2 places in Roam: left sidebar and blocks. For Athens, we'd like to have a 3rd: the right sidebar. I've implemented partial DnD twice already for blocks (which is harder than left or right sidebar as blocks can be nested) using vanilla JS event handlers, neither very well:

1.  #183 global event listeners. Wasn't able to drop above the 0th block.
2. #232 #234 local event listeners. Now unable to drop below the last block.

Needing to be able to drop above or below a block is a classic "wall and room" problem. If you have 2 "rooms", you have three "walls" or drop areas. I may be overthinking this. But [Sortable.js has special treatment of lastChild](https://github.com/SortableJS/Sortable/blob/master/src/Sortable.js#L228).

It seems like Roam has one `div` at each vertical drop area on the y-axis (imagine a ladder). The x-axis determines which depth in the tree you can drop at, from outermost parent to innermost child.

Workflowy has the same functionality, except rather than having a ladder of drop areas, they have a single drop area that with `positioning: absolute` that updates its `top` and `left` coordinates.

Dynalist does it a 3rd way. They have `is-showing-top-divider` `is-showing-bottom-divider` and `is-showing-bottom-children-divider`. They don't allow dropping at any depth of block, only on innermost block. They also don't allow drag across multiple depths - parent is necessarily selected if you drag down.

- https://lukasoppermann.github.io/html5sortable/index.html
- https://sortablejs.github.io/Sortable/
