### ISSUE TITLE
Slash Commands / Inline Search

### ISSUE THREAD

**Issue by tangjeff0** [athensresearch/athens#245]
# Tasks

- [ ] determine when to show/close typeahead
- [ ] determine best way to store and update search string
- [ ] filter on search results
- [ ] position typeahead

# Background

I've grouped these two together because they seem similar at the moment. However, it's possible that they have separate implementations.

**Comment by tangjeff0** [comment]
Forgot about #59 XD
