### ISSUE TITLE
Extensions (later)

### ISSUE THREAD

**Issue by HaojiXu** [athensresearch/athens#291]
Related: #279 
To be done after v1 is ready!

## Todo List
- [ ] Talk about how we'd like athens extensions to be (for example, using something similar to Roam's API or something else?)
    - [ ] How it links to custom DB queries exposed to users
    - [ ] How it links to custom components
- [ ] Figure out how to run them efficiently and securely - for example, using a sandboxed eval, or just using eval, or pre-compile, or else?
- [ ] Docs about extensions!

Here's a simple prototype of how extensions might work:
```javascript
// An Example Athens Extension

Athens.api.onInit(() => {
    // Log something in console
    console.log("Example extension loaded!");

    // Add a slash command
    Athens.api.commands.add("meaningoflife", (currentNode) => {
        currentNode.set(":block/string", "42").then(() => {
            alert("42");
        });
    });

    // Add a custom component
    Athens.api.components.add({
        name: "component-wikidata",
        match: "wikidata\:\ .*",
        render: (content, uid) => {
            wdcontent = content.substr(9);
            "<button onclick='window.navigate(\"https://wikidata.org/wiki/" + wdcontent + "\")'>Wikidata: Q" + wdcontent + "</button>";
        }
    });
});

// Listen to events
Athens.api.events.subscribe(":editing/uid", (editingUid) => {
    console.log("Now editing: " + editingUid);
})
```

**Comment by HaojiXu** [comment]
Closing - discuss at #63!
