### ISSUE TITLE
Athens Feature Review Checklist

### ISSUE THREAD

**Issue by shanberg** [athensresearch/athens#294]
I expect this to change over time, and for much of it to become unit tests at some point. Until then, it can be a reference for minor features and issues to be aware of when making functional changes.

### Creating a new page
- [x] Is it obvious for a new user how to create a new page?
- [x] Can I create a new page from an empty link?
    - [ ] Does the page have all the correct features when I navigate to it?
        - [x] Proper title?
        - [ ] Proper title appearance when editing?
        - [x] Expected Linked/Unlinked references?
- [x] Does the page look correct like an empty canvas for my thoughts?
    - [ ] If I created the page with a title (e.g. by creating a bidi-link and clicking it), is the cursor in the start of the first text block?
    - [ ] If I created the page without a title, is my cursor in the title textarea?
    - [x] What is visible at start?
- [ ] What happens if I leave the page empty?

### Editing Block Text
- [ ] Is text editing responsive and predictable?
- [x] Is my cursor position predictable?
- [x] Are the types of block text content distinct and their UX capabilities obvious?
    - [x] Inclusions
    - [x] Presentations
    - [x] Plain text
    - [x] Inline placements
    - [ ] …
- [x] Can I delete forward?
- [ ] Is it clear what will happen when I click on each area of a block?
    - [ ] Clicking links goes to page or block or web page
    - [ ] Clicking todo checkbox toggles checkbox
    - [ ] …
- [ ] Cut works
- [ ] Copy works
- [ ] Paste works
- [ ] Shift-copy copies reference to current block

### Moving The Cursor Through Block Text
- [x] Cmd(ctrl) left arrow/right arrow moves to the start or end of text
- [x] Arrow up/Arrow down moves up and down in the block direction, and through blocks at ends
- [x] Alt-left/Alt-right moves inline by one word, and through blocks at ends
- [x] Holding shift while moving the cursor creates a selection

### Rearranging Blocks
- [x] Can I move a block with the keyboard?
- [ ] When I want to move a block with the keyboard, is it clear where it will move in the tree?
- [ ] When I have moved a block with the keyboard, Is it clear where it has moved in the tree?
- [x] Can I move a block with drag-drop?
- [x] When I move a block with drag-drop, is it clear where it will move in the tree?
- [x] When I move a block with drag-drop, is it clear where it has moved in the tree?

### Scrolling a Page
- [x] Can I scroll with each of the expected keyboard features?
    - [x] Spacebar/Shift-spacebar
    - [x] Page Up/Down
    - [x] Home/End
    - [x] Arrow Up/Arrow Down
    - [x] When my cursor reaches the top or bottom of the page, does the page scroll so the cursor is visible?
    - [x] Using the mouse wheel, when cursor is not over a special object

### Dropdowns/Popovers/Menus
- [ ] Can they be dismissed in all the expected ways?
    - [x] Dismiss by pressing Esc
    - [ ] Dismiss by clicking anywhere except the menu
- [x] Can they be navigated with the keyboard?
- [x] Are the labels full and clear?
- [ ] Are the active, focused, selected, hovered, and disabled menu item states distinct?
- [x] Do they stay within the browser viewport even when created close to the edge?
- [ ] Do they prevent page scrolling when present?
- [x] Does arrowing the selection past the first or last item in a list loop back to the opposite end of the list?

### Slash Menu
- [x] Does it provides the options I expect?
- [x] Can I navigate the options quickly and intuitively?
- [x] Can I filter the options with the keyboard?
    - [ ] Can I filter with fuzzy search?
- [x] Is the selected item clear, so I can be confident in what I’m doing?
- [x] Can I easily dismiss the menu if I opened it by mistake?
- [ ] Does the slash I used to open the menu stay? Should it?

### Using Athena
- [x] Is it reasonably fast?
- [x] Are its capabilities made immediately clear?
- [x] Is the main input focused when the window appears?
- [x] Do its capabilities map to the capabilities afforded to the user elsewhere?
- [x] Does Athena feel obvious, useful, and helpful?
- [ ] Does Athena feel powerful?
- [ ] …

**Comment by HaojiXu** [comment]
Also: a reddit user reported that if you type something in an empty block then try indenting it using 'tab', the block content would disappear then reappear after a visible delay. I'm able to reproduce this issue. Maybe add it to the feature checklist?
