### ISSUE TITLE
Slash commands

### ISSUE THREAD

**Issue by tangjeff0** [athensresearch/athens#59]
# Tasks

- [x] get [caret position](https://github.com/athensresearch/athens/issues/59#issuecomment-634390329) (necessary for in-line search as well with `[[]]` and `(())`]) [tutorial](https://medium.com/@jh3y/how-to-where-s-the-caret-getting-the-xy-position-of-the-caret-a24ba372990a)
- [x] use arrow keys to scroll through options
- [x] typeahead filter that narrows possible options
- [x] on `enter` or click, expand text
- [x] determine when to show/close typeahead (compare Roam and Notion)
- [x] determine best way to query (by index of input value or separate string?)

Many small interaction / implementation questions. Lots of overlap with inline-search - `[[]]` `(())`. Slack and Discord are not great examples because they only allow commands if you start input with a slash. 

### Original Post

<details>
  <summary>Click to open</summary>

# Feature

- Typing `/` pops up a list of commands as in Slack, Notion, Roam, etc.
- You can select a command by either clicking on one of them
- Or by scrolling through the list with up and down arrows and selecting with enter.
- Upon selection, text expands. Probably a map of key-values.

# Demo

![slash-commands](https://user-images.githubusercontent.com/8952138/82100110-ece7bf80-96d6-11ea-9b29-1d2fb601b0e7.gif)
<details>

**Comment by anonimitoraf** [comment]
Hey man, interested in implementing this. I've only cloned the repo so I'll need a bit of time to get up to speed with it

**Comment by anonimitoraf** [comment]
@tangjeff0 I'm getting an "Invalid invite" when I click the Discord link :( Is it because there are already 100 members?

**Comment by tangjeff0** [comment]
Try this @anonimitoraf : https://discord.gg/7ztV74d

**Comment by anonimitoraf** [comment]
Thanks. I filled in the ClojureFam form (as a learner) and one of the steps was to say hi on the #introduction channel but the discord server doesn't seem to have that channel?

Concerning this specific task, when I start up the app, I don't see any way to create a new entry/doc. Did I just not find it or it just doesn't exist yet?

**Comment by roryokane** [comment]
@anonimitoraf You’re right, there’s no way to create a new page yet in Athens, nor a way to create a new block (bullet point) within a page.

Slash commands are also expected to work when typing within an existing block, so you could develop it there. However, we’re still implementing that feature (issue #60 “Editable blocks”). You might notice a bare-bones form of editing available in the current app using `contentEditable`, but we’re planning to rewrite the editing capability to use textareas instead.

Since the change to textareas could impact the triggering, display position, and keyboard capturing of the slash commands popup, I think it’s best to wait for #60 before starting on this.

**Comment by tomisme** [comment]
Here are some resources for placing the popup:

 - https://stackoverflow.com/questions/6930578/get-cursor-or-text-position-in-pixels-for-input-element
 - https://github.com/component/textarea-caret-position

As far as I know the only way to do it is to create temporary <div>s as described in the links above. I believe that's how twitter does @ popups, not sure about Roam yet.

**Comment by anonimitoraf** [comment]
@roryokane I see, thanks!

@tomisme Thanks for that too!

**Comment by shanberg** [comment]
Some desires for slash commands/dropdowns:

**Typing while in slash menu should filter list of items**
Maybe we can do this by disabling items rather than removing from list, as long as the lists are short (>7 items)

**Text expansions should include a space at the start if not at the start of a block**
I believe this is common practice in similar editors. Are there any exceptions to this?

**Often typing [[ quickly gives me this: [][]. Same with ((**
Performance issue?

**Can’t dismiss dropdowns**
In testing I ended up with a bunch of visible dropdowns and no way to dismiss them.
