### ISSUE TITLE
doc: automated release notes / changelog

### ISSUE THREAD

**Issue by tangjeff0** [athensresearch/athens#642]
- https://github.com/conventional-changelog/conventional-changelog: root monorepo

- https://github.com/conventional-changelog/standard-version: cli tool that automatically bumps version. Before I was manually updating the package.json version, writing a commit, and creating a tag each time I needed to create a new release for Athens. If I forgot a tag, it sometimes wouldn't work. Not a big deal, but manual.

- https://github.com/conventional-changelog/commitlint: Checks whether the commit message is valid or not. Necessary in the case where a contributor doesn't use a conventional commit. For instance, only 4 of the previous 6 commits would get added to the changelog.
	- `test(parser): add test for raw-url for #636 (#641)` - "test" is not a conventional commit
	- `fix(router)598 shift clicking tag opens right hand sidebar` - missing colon

![image](https://user-images.githubusercontent.com/8952138/107865051-b5e63c00-6e17-11eb-8fb6-cae5c3a3f3e1.png)

# Tasks

- [ ] enforce via Action or git hook
- [x] define conventional commits
- [ ] update CONTRIBUTOR docs

**Comment by tangjeff0** [comment]
https://twitter.com/gusmmm/status/1364862696886255618?s=20

**Comment by tangjeff0** [comment]
Now can use `yarn update` to auto bump package version and update CHANGELOG
