### ISSUE TITLE
Daily Notes

### ISSUE THREAD

**Issue by tangjeff0** [athensresearch/athens#66]
# Tasks

- [ ] calendar button to select any date
- [x] show alert when user tries to edit title
- [x] hide linked/unlinked references if there are none #191 
- ~ notional dates
- ~ jump to Timeline
- [X] scroll to create new page #212 

# Original Post

<details>
  <summary>Click to open</summary>

When a user open their Roam, they should automatically generate a notes page for the current 
date. User should be able to scroll down to previous days. 

Note: these Daily Notes pages are different from other pages in that their titles are not allowed to be changed. Attempt to do so leads to a warning.

# Warning
![Screen Shot 2020-05-15 at 7 44 29 PM](https://user-images.githubusercontent.com/8952138/82104328-7fdb2680-96e4-11ea-9de4-d0fa2cdd155f.png)

# Screenshot
![image](https://user-images.githubusercontent.com/8952138/82104275-40acd580-96e4-11ea-8be8-631c24f71d64.png)

</details

**Comment by jeroenvandijk** [comment]
TASKS

- [ ] Core work: scrolling down and opening a new page (add [onscroll event listener](https://javascript.info/onscroll))
- [ ] Add warning when title of date page is changed (possibly a regexp check on the page title is enough for this. Maybe no need to check if it is a special page)
- [ ] Bonus: when you are in the `Daily Notes` view and times passes into the next day (in your timezone), a new day should be added. Could be done by triggering a re-render in X seconds via (setTimeout ...)
- [ ] Bonus: to keep the app performant endless scrolling down should also clean up day views on top. With scrollup event these views would have to be added again

**Comment by Bardia95** [comment]
Working on it with @pinned5th as part of ClojureFam, looking to get a working version by end of week!

**Comment by tangjeff0** [comment]
@Bardia95 that's awesome — glad you are setting a deliverable for yourself! I'm personally more curious about how you two are mapping these scopes, and what scopes will be discovered and refactored over time. Please update this issue at various checkpoints so you can teach the rest of us :)

**Comment by Bardia95** [comment]
@tangjeff0 right now, the path is uncharted, my plan for today is to experiment with how we could accomplish this feature and update with any findings, and then once we've scoped out a bit will update with what we're each working on. We have planned a pair programming session once we've scoped out more granularly

**Comment by tangjeff0** [comment]
> Working on it with @pinned5th as part of ClojureFam, looking to get a working version by end of week!

How are scopes progressing @Bardia95 ?

**Comment by Bardia95** [comment]
Sorry I've been unexpectedly swamped with work from my job. But I'm focussing on the issue all day tomorrow and will have some commits to look over. I've made some notes of things that need to be considered in the mean time: 

- Create new page at 12:00 am (localized) (need to get location / timezone) every day with title being the date
    - Make sure you can't edit the title of this page
        - Show warning
    - Everything else is like a normal page
- Display pages on Daily Notes page
    - Only show days from current day and before (no future dates)
- Have the Daily Notes page update at 12:00 am when the new page is created
- What happens when Athens is first opened?
    - Creates new page with the day
- What happens when a user doesn't log into Athens for a few days — are those dates not created?
    - No, the daily notes is only created when on the app
        - On connect
            - Query db to see if page exists of today
                - (maybe make this every few seconds)
                    - If so just update
                    - If not create new page and update
- What happens when a user creates a date in the future, and then that date arrives?
    - Covered in above

**Comment by Roc-kit** [comment]
Hi,  Where's the calendar button? I can't find it 😂
