### ISSUE TITLE
Self-Hosted Real-Time Collaboration

### ISSUE THREAD

**Issue by jsmorabito** [athensresearch/athens#840]
- Related: #930 #1075 #1074 https://github.com/athensresearch/athens/discussions/1082

# Issues ([Project Board](https://github.com/athensresearch/athens/projects/16))

- [ ] fix bad state that occurs from multiple writers #1140
- [ ] importing existing index.transit into backend db #1101
- [ ] parameterize `token` #1100
- [ ] presence UI: the "Online" functionality is wrong - who is on the block and page
- [ ] auto-reconnect. if computer goes to Sleep, have to manually reconnect #1102
- [ ] merging athens-backend into main athens and archiving athens-backend
- [ ] set HTTP ports in a straightforward way
- [ ] set port for nREPL
- [ ] fix hard code for filepath
- [ ] fix undo/redo

# Live Server

Setup a remote EC2 instance. Anyone can connect with the following credentials:

`address`: ec2-3-16-89-123.us-east-2.compute.amazonaws.com
`token`: x

**Comment by arkRedM** [comment]
>  merging athens-backend into main athens and archiving athens-backend

why?

Other issues are in https://github.com/athensresearch/athens/discussions/1082

**Comment by tangjeff0** [comment]
> why?

We want to keep front and backend changes synced up right now as a monorepo.

**Comment by arkRedM** [comment]
I agree it can ease things that way.
But there is not much interaction between the two systems other than data format.
Things I want to point out.

Why split?
1. too many unnecessary commits for someone looking at one of backend or frontend
2. Simple separation of concerns 
3. Independent evolution
    a. changing version of deps without fear of breaking something in other system
    b. Focusing/attracting the right dev to the right place easily.
    c. Optimizations are different etc.

Why monorepo?
1. Dev workflow(specifically with PRs. not much effect on working on each)
2. Shared functionality 

Other than this, lein can easily handle combining without much tweaking.

**Comment by tangjeff0** [comment]
Zooming out to a higher-level architecture view, there are two broad kinds of models:

- Single-writer (e.g. Datomic): front-end datascript db is read-only, backend single writer will reject new transactions if the last-tx-id is wrong (because the constructed tx-data might be wrong)
- Multiple-writers (e.g. [Web After Tomorrow](https://tonsky.me/blog/the-web-after-tomorrow/)): client is always responsive to writes, and somehow conflicts are all eventually resolved even if offline mode (Tonsky calls offline a special case of "infinite lag")

Right now, @neotyk and I are thinking about moving to a single-writer model. This doesn't give us local-first conflict resolution when real-time collaboration is expected, but that's fine for now. This is still quite difficult, and hopefully Athens can eventually help pioneer this technology. Today, we are confident that single-writer is a tractable problem with up to a hundred concurrent users.

https://github.com/athensresearch/athens/discussions/1082#discussioncomment-711294

**Comment by arkRedM** [comment]
https://github.com/athensresearch/athens/issues/840#issuecomment-831695838

More points? Something we might be overlooking? @neotyk @tangjeff0

**Comment by arkRedM** [comment]
No more points for or against #840 @neotyk @agentydragon @tangjeff0

**Comment by agentydragon** [comment]
Re. https://github.com/athensresearch/athens/issues/840#issuecomment-831695838:

- I think "too many unnecessary commits" is not a good argument. I could just as well say "I'm working on the parser, I don't want to see the history of component rendering in the log". If you want to see the history of a particular part, you can always do `git log your/directory`.
- One argument for monorepo (and against "independent evolution") is that in a monorepo, you can do *atomic changes*. Say you want to rename a field in the database from `x` to `y`, which affects both frontend and backend. In a monorepo, you can do that in a single commit, so you have a guarantee that any commit in the linear history of the main branch is consistent and works. If you do this in 2 repos, with commit `abc123` doing it in frontend and `cba321` in the backend, you then have a state where only versions before `abc123` of frontend and before `cba321` of backend will work together, and only versions after `abc123` and `cba321` respectively. This makes it harder to, for example, make integration tests that spin up both a backend and a frontend. 
- "Optimizations are different": I assume Lein would also allow you to build different binaries from one repo with different optimizations. If you mean the frontend and backend code might be written differently to optimize for different things, that's still possible in a monorepo.
- *Divergence* (again, against "independent evolution"): if you have 2 repositories that do not share code, it's way easier for someone to, say, fix a bug in one repo, but not in another repo. The more code in 2 repos diverges, the harder it is to make sure it works the same way, and unless you have tests that test the 2 repos together (... at which point you might as well have a monorepo), there's no automation preventing this from happening .

**Comment by arkRedM** [comment]
Agree with your most of the ideas.

What about the fact that in their current state backend is very volatile?
- can change a lot of deps and independent evolution of deps can become a issue.

This is what I'm more worried about. Could never be the case we hit them.

By optimizations - referring to structuring and all the files that don't concern other side(builds/docker/env etc). As I've said lein can easily work with multiple systems with ease.

Regardless there's a good incentive for monorepo. Will start on it once the backend gets to a good state.

**Comment by agentydragon** [comment]
> What about the fact that in their current state backend is very volatile?

I think for now developing in separate repo is okay as long as we eventually merge when it stabilizes a bit.

In a monorepo, one option is just following the regular process. Add a basic server in a pull request, then do more things as more pull requests. It means you have to be a bit more principled, because your code has to get through review. But I think that's actually good because that way more people will end up with a good understanding of the code, you're encouraged to write tests, etc.; it's harder to get to understand code if it just lands in the repo as "here, I worked on this for 3 months, please merge there 200k lines of code". It's easier if you see it evolve.

Another option is we could create a new directory in the monorepo and give you the ability to merge pull requests into that directory without review from others. But that would take more setup.

So overall I'm fine with separate repo that we merge eventually :)

(Also, when do you plan to do that? Do you maybe have some list of outstanding TODOs?)

> * can change a lot of deps and independent evolution of deps can become a issue.
> 
> This is what I'm more worried about. Could never be the case we hit them.

I don't know Lein enough, but I'd hope we could have separately managed dependencies for the backend and frontend, so that they could use different versions of packages, if needed. Or that if backend doesn't use, say, Stylefy, that it wouldn't slow down its build. But there's reasons to want to keep versions of dependencies tied together between backend and frontend, to avoid diverging behavior.

> Regardless there's a good incentive for monorepo. Will start on it once the backend gets to a good state.

👍
Thanks for all the work on this, I think it's both the most complicated and most important work right now for Athens :)

**Comment by arkRedM** [comment]
> outstanding TODOs

Stability and consistency are the main ones. 

> lein 

Lein does handle deps but most of clojure libs work with clj and cljs and are generally written with reader conditionals(https://clojure.org/guides/reader_conditionals). Since some deps are more focused on clj side and uneven support from cljs, rarely we run into something that works with clj and not with cljs or vice versa. 

And it causes downstream issues in building jars or packing js files. Although those situations are not very common.

**Comment by tangjeff0** [comment]
Closing this Epic, sticking to just project board for now. https://github.com/athensresearch/athens/projects/16
