### ISSUE TITLE
Pages

### ISSUE THREAD

**Issue by tangjeff0** [athensresearch/athens#96]
# Tasks

- [x] delete page
- [x] add to shortcuts
- [x] merge pages if editing a non-date page. show confirmation alert #61 #62 
- [x] hide linked/unlinked refs if in Daily Pages view #66 
- [x] prevent title editing if date page. show warning alert
- [ ] button to create a new page? can already create pages in Athena
- [ ] filters #65

**Comment by nthd3gr33** [comment]
Please comment @itsrainingmani @alaq so I can assign our team to this issue.

**Comment by itsrainingmani** [comment]
Let's go @nthd3gr33 !

**Comment by alaq** [comment]
👋

**Comment by nthd3gr33** [comment]
We started looking into the shortcut part of this issue, but we have discovered that quite a bit was already done. So we will likely move on to the deleting pages part of the issue.

We have questions about implementation of this feature:
What is the expected UX for it? In roam, you check pages in the all pages list and then you can bulk delete
Plus what happens to empty pages that have no links to them
do we keep them? eagerly delete them?

**Comment by nthd3gr33** [comment]
(Fat fingers, sorry 😅 )

We started looking into the shortcut part of this issue, but we have discovered that quite a bit was already done. So we will likely move on to the deleting pages part of the issue.

We have questions about implementation of this feature, specifically in regards to expected UX for deleting pages:  
1. In Roam, you can check pages in the All Pages list and then you can bulk delete. Do we also want to implement that here? Or are bulk operations out of the scope of this issue?
1. What happens to empty pages that have no links to them. Do we keep them? Eagerly delete them?
1. If you delete a page, should all corresponding links to it be deleted? (this is current Roam behavior)

**Comment by tangjeff0** [comment]
The main part remaining for shortcuts is decrementing all the indices after the index that was removed, which is NBD.

1. Bulk operations are part of All Pages, out of scope.
1. Can you give me an example?
1. Yes, and we have all the `:block/uid`s in linked references.

Made #292 for you three. I also think you can assign yourselves to the issue now. I had to add the athens repo to the devs team.

**Comment by alaq** [comment]
> 2. Can you give me an example?

We're thinking of pages that were created by a link, but the link was later removed. Here is what is happening in Roam:
1. Create new block with link to [[new page]]
1. `new page` is visible in All Pages
1. remove link to `new page` in new block
1. `new page` is no longer visible in All Pages (it has been deleted)

**Comment by tangjeff0** [comment]
Yeah, we should delete orphan pages.

**Comment by hmaurer** [comment]
I am looking through issues for a good first contribution. This seems interesting, have there been developments since your last comment @tangjeff0 ?

**Comment by tangjeff0** [comment]
Hi @hmaurer, Pages are mainly done. There are better first issues on https://github.com/athensresearch/athens/projects/4.
