### ISSUE TITLE
Left Sidebar

### ISSUE THREAD

**Issue by tangjeff0** [athensresearch/athens#99]
For v1, the only remaining task is drag and drop to re-order sidebar. 

### Tasks

- [x] Drag to re-order shortcuts. see #183 
- [x] create Athena affordance. Not entirely sure what this interaction would look like
- [x] expand/collapse toggle
- [x] import into actual project - #125
- [x] mock datoms #118 
- [x] buttons #119
- [X] - collapsed stick menu #134 
- [X] expanded #122 
- ~ **Appearance** - ~~screenshot and explanation below~~ sticking with one appearance for v1
- ~ **Recents** - ~~UI is same as Shortcuts. Could be persisted in `localStorage` as described in **Appearance**~~ now showing recents in Athena: #208 
- ~ **Settings** - ~~TBD what settings will do or what they will look like~~ can't work on this until we have settings

![left-sidebar](https://user-images.githubusercontent.com/8952138/83577055-3753a380-a501-11ea-8eb2-2f2faa27746c.png)

**Comment by jacobmorse** [comment]
Seriously considering changing from a left sidebar navigation to a horizontal navbar at the top.

**One option would be to supplement the left sidebar:**
<img width="2085" alt="Group 144" src="https://user-images.githubusercontent.com/48877/83154690-0ec54700-a0c6-11ea-808b-5d5e8b6828d3.png">

**The other option (my current preference) is to replace it entirely and leave the horizontal real estate entirely for content editing.**
<img width="2085" alt="Group 188" src="https://user-images.githubusercontent.com/48877/83154800-2c92ac00-a0c6-11ea-93d3-d9299e495b5e.png">

**Comment by tangjeff0** [comment]
### Buttons

  1. Can only use pseudo selectors like `:&:hover` when using proper css, not inline.
    - this disrupts the inline `+style` pattern we've been using
  1. Can't use `with-styles` in proper css because it returns a nested map `{:style {}`} but
  proper css wants a flat map
    - There's an easy solution to this: (:style (with-styles {})))
  1. Opacity is a pain because you aren't adding opacity to the element inline. Rather, you must
  use the `opacify` function with the right color. Furthermore, you must find the opacity index.

  The combination of all the above make buttons annoying.

### Mock Datoms

  This isn't nearly as tragic as buttons, just a few things left to do.

  - Create helpers to let each DevCards easily instantiate its own DSDB
  - Refactor helpers to let DevCards easily use real data, by pulling in an example db.

**Comment by jacobmorse** [comment]
I attempted a move to explicit hex colors vs. opacity when evolving the style guide. I'm not sure if this helps with the above. 

![image](https://user-images.githubusercontent.com/48877/83689586-ea310980-a5b4-11ea-8590-afa48cbe8645.png)
